/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// Полностью из файловой системы: категории берутся из _category_.json в папках,
// index.mdx каждой папки автоматически становится её индексом (не дублируется в списке).
// Новый урок = просто новая папка в docs/lessons/ — появляется в меню сам.
const sidebars = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};
export default sidebars;
