/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coursesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'courses',
    },
  ],
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  helpSidebar: [
    {
      type: 'autogenerated',
      dirName: 'help',
    },
  ],
};

export default sidebars;