/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Revit Lessons',
      link: {type: 'doc', id: 'lessons/index'},
      items: ['lessons/walls-different-materials/index'],
    },
    {
      type: 'category',
      label: 'Courses',
      items: [{type: 'autogenerated', dirName: 'courses'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Help',
      items: [{type: 'autogenerated', dirName: 'help'}],
    },
  ],
};
export default sidebars;